name: Auto Label PR based on Base Branch

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - dev
      - staging
      - main

permissions:
  pull-requests: write

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add label based on base branch
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            ${{ github.event.pull_request.base.ref == 'dev' && 'dev' || '' }}
            ${{ github.event.pull_request.base.ref == 'staging' && 'staging' || '' }}
            ${{ github.event.pull_request.base.ref == 'main' && 'main' || '' }}